tasks/urls.py
from django.urls import path
from . import views

app_name = "tasks"
urlpatterns = [
    path("",views.index,name="index"),
    path("add/",views.add,name ="add"),
    path("<int:task_id>/edit",views.edit,name ="edit")
]

web_app/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('tasks/',include('tasks.urls'))
]

tasks/models.py
from django.db import models

# Create your models here.
class Task(models.Model):
    task = models.CharField(max_length= 50)

    def __str__(self):
        return f"{self.task}"

tasks/views.py
from django import forms
from django.shortcuts import render, redirect
from django.http import HttpResponseRedirect
from django.urls import reverse
from .models import Task
# Create your views here.

class NewTaskForm(forms.Form):
    
    task = forms.CharField(label="",widget= forms.TextInput
                           (attrs={'placeholder':'New Task'})
                           )
                           
def index(request):
    return render(request,"tasks/index.html",{
        "tasks": Task.objects.all(),
        "form": NewTaskForm()
    })

def add(request):
    if request.method == "POST":
        form = NewTaskForm(request.POST)
        if form.is_valid():
            new_task = form.cleaned_data["task"]
            insert_task(new_task)
            return HttpResponseRedirect(reverse("tasks:index"))
        else:
            return render(request,"tasks/index.html",{
                "form": form
            })
    
    return render(request, "tasks/add.html",{
        "form":NewTaskForm()
    })


def edit(request, task_id):
    task = Task.objects.get(pk = task_id)
    if request.method == "POST":
        form = NewTaskForm(request.POST)
        if form.is_valid():
            if "save" in request.POST:
                task = form.cleaned_data["task"]
                update_task(task,task_id)
                return redirect(reverse("tasks:index"))
        if "delete" in request.POST:
            delete_task(task_id)
            return redirect(reverse("tasks:index"))
        else:
            return redirect(reverse("tasks:index"))
    return render(request, "tasks/edit.html",{
        "task": task,
        "form":NewTaskForm()
    })

def delete_task(task_id):
    task = Task.objects.get(pk = task_id)
    task.delete()

def update_task(task,task_id):
    current = Task.objects.get(pk = task_id)
    current.task = task
    current.save()

def insert_task(task):
    t = Task(task = task)
    t.save()

tasks/templates/tasks/edit.html
{% extends "tasks/layout.html" %}

{% block title%} 
<title>Edit Task</title>
{% endblock %}

{% block body %}
    <h1>Editing Task "{{task}}"</h1>
    <form action="{% url 'tasks:edit' task.id %}" method="post">
        {% csrf_token %}
        {{form}}
        <input type="submit" value="Save" name = "save">
    </form>
    <br>

    <form action="{% url 'tasks:edit' task.id %}" method="post">
        {% csrf_token %}
        <input type="submit" value="Delete" name = "delete">
        <input type="submit" value="Cancel" name = "cancel">
    </form>
    
    
{% endblock %}

tasks/templates/tasks/index.html
{% extends "tasks/layout.html" %}

{%block title%} 
<title>Tasks</title>
{% endblock %}

{% block body %}
    <h1>To-Do List</h1>
    <ul>
        {% for task in tasks %}
            <label><input type="checkbox"> {{task}} <a href="{% url 'tasks:edit' task.id %}">Edit</a></label><br>
        {% empty %}
            <li> No tasks.</li>
        {% endfor %}
    </ul>
    <br>
    <!-- <a href="{% url 'tasks:add' %}"> Add a tasks</a> -->
    <!-- <br>
    <br> -->
    <form action="{% url 'tasks:add' %}" method="post">
        {% csrf_token %}
        {{form}}
        <input type="submit" value="Add">
    </form>
    <!-- remove tasks form -->
    <br>
{% endblock %}

tasks/templates/tasks/layout.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    {%block title%} {% endblock %}
</head>
<body>
    {% block body %}
    {% endblock %}
</body>
</html>